name: lunaR CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install R
      run: sudo apt-get install -y r-base
    - name: Install fftw
      run: |
        R --version
        wget http://www.fftw.org/fftw-3.3.8.tar.gz
        tar -xzvf fftw-3.3.8.tar.gz
        cd fftw-3.3.8
        ./configure --enable-shared --prefix=/home/runner/work/luna1/luna1/fftw-3.3.8/
        make
        make install
        cd ..
    - name: Install luna-base
      run: |
        git clone http://github.com/remnrem/luna-base.git
        cd luna-base
        make FFTW=/home/runner/work/luna1/luna1/fftw-3.3.8/
        cd ..
        ls -lrta
        R --version
        echo "Printing luna base listing next"
        ls -lrta luna-base/
    - name: make lunaR
      run: |
         sudo R -e "install.packages('plotrix', repos='http://cran.rstudio.com/')"
         sudo R -e "install.packages('geosphere', repos='http://cran.rstudio.com/')"
         ls -lrta /home/runner/work/luna1/luna1/fftw-3.3.8/lib/
         cd ..
         sudo LUNA_BASE=/home/runner/work/luna1/luna1/luna-base FFTW=/home/runner/work/luna1/luna1/fftw-3.3.8 R CMD INSTALL luna
